db_host: <hostname>
db_user: <username>
db_password: <password>
db_name: <dbname>

db_engine: <mysql|postgres|csv>

analyzers: [ FlowStat ]
FlowStatConfig: 
- { imgDir: 'imgs/', rrdDir: 'rrd/' }
- { reportName: 'Packets', idx: 7, filter: ' ' }
- { reportName: 'Bytes', idx: 6, filter: ' ' }

