db_host: <hostname>
db_user: <username>
db_password: <password>
db_name: <dbname>
db_stepsize: <seconds>

db_engine: <mysql|postgres|csv>

workdir: workdir

# ---- FlowStat configuration

analyzers: [ FlowStat ]
FlowStatConfig: 
- { imgDir: 'imgs/', rrdDir: 'rrd/' }
- { reportName: 'Packets', idx: 7, filter: ' ' }
- { reportName: 'Bytes', idx: 6, filter: ' ' }

# ----- CSVWriter configuration

analyzers: [ CSVWriter ]
CSVWriterConfig: { outputfile: 'filename.csv' }


#  ----- Subnet-Grapher

analyzers: [ SubnetGrapher ]
SubnetGrapherConfig: { subnetCSV: 'subnetconfig.csv', outputdir: 'sgDir/' }
